spring.application.name=word-sync-service

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=word_service
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Microsoft Graph OAuth2 Settings
spring.security.oauth2.client.registration.graph.client-id=${GRAPH_CLIENT_ID}
spring.security.oauth2.client.registration.graph.client-secret=${GRAPH_SECRET_KEY}
spring.security.oauth2.client.registration.graph.scope=openid, profile, Notes.Read
spring.security.oauth2.client.registration.graph.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.graph.redirect-uri=http://localhost:8080/login/oauth2/code/{registrationId}


# Provider details for Microsoft
spring.security.oauth2.client.provider.graph.authorization-uri=https://login.microsoftonline.com/common/oauth2/v2.0/authorize
spring.security.oauth2.client.provider.graph.token-uri=https://login.microsoftonline.com/common/oauth2/v2.0/token
spring.security.oauth2.client.provider.graph.user-info-uri=https://graph.microsoft.com/oidc/userinfo
spring.security.oauth2.client.provider.graph.user-name-attribute=sub

# Local
app.dict.file-path=D:/word-sync-service/word-sync-service/my-words.txt